# Generated by Django 4.2 on 2025-05-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon',
            field=models.ImageField(upload_to='about_icons/'),
        ),
        migrations.AlterField(
            model_name='aboutfeature',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
