# Generated by Django 4.2 on 2025-05-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texas', '0002_alter_aboutfeature_icon_alter_aboutfeature_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutFeature',
            new_name='AboutFeatures',
        ),
    ]
