# Generated by Django 4.2 on 2025-05-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texas', '0003_rename_aboutfeature_aboutfeatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutFeatures',
            new_name='AboutFeature',
        ),
    ]
