# Generated by Django 4.2 on 2025-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas', '0004_rename_aboutfeatures_aboutfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkout')),
            ],
        ),
    ]
