# Generated by Django 4.2 on 2025-05-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas', '0005_checkoutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
