# Generated by Django 4.2 on 2025-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas', '0006_accordingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='CEO, Company', max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
